sudo: false
language: php

notifications:
  email: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest

install:
  - composer install --prefer-dist
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - WP_MULTISITE=0 ./vendor/bin/phpunit
  - WP_MULTISITE=1 ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=phpcs.xml ./
